### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by Elaineok** [yh-pengtu/GuidedMix-Net#1]
Hey，when will the code be released?

**Comment by yh-pengtu** [comment]
We will release the code after the AAAI deadline because some other works hinder my steps. Thanks for your attention!!

**Comment by DuowenC** [comment]
Dear author,  can i please ask when will the code be released approximately?

**Comment by ghost** [comment]
Codes of GuidedMix-Net can be found in https://github.com/yhpengtu/GuidedMix-Net
