### ISSUE TITLE
how to set lambda values < 0.5 ?

### ISSUE THREAD

**Issue by CuberrChen** [yh-pengtu/GuidedMix-Net#3]
Hi, according to the paper, ```λ``` is the parameter from the ```Beta (α, α)``` distribution and set ```λ=min(λ, 1 - λ)```. 

What we can do is set the value of α, is it? This doesn't seem particularly clear.

Looking forward to your reply.

Best,

**Comment by yh-pengtu** [comment]
lambda = Beta(alpha, alpha)
lambda= min( lambda  , 1- lambda  )
while  lambda   >= 0.5:
   lambda  = Beta( lambda  ,  lambda  )
   lambda  = min( lambda  , 1- lambda)

Best,

xbchen ***@***.***> 于2022年3月23日周三 18:00写道：

**Comment by CuberrChen** [comment]
thanks
